baseURL = "https://blog.gao-chuan.com"
theme = "hugo-bearblog"

title = "高川 | Blog"
author = "高川"
copyright = "Copyright © 2026, 高川."
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "尝试理解一切；有时候写下来。"
  favicon = "images/favicon.jpg"
  images = ["images/favicon.jpg"]
  title = "高川 | Blog"
  hideMadeWithLine = true

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
